import NextTopLoader from "nextjs-toploader";
import { Header } from "./(components)/Header";

import { Gothic_A1, Inter, Noto_Sans } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";
import { Footer } from "./(components)/Footer";

const inter = Inter({ subsets: ["latin"] });
const notoSans = Noto_Sans({ subsets: ["latin"] });
const gothic = Gothic_A1({ subsets: ["latin"], weight: ["500"] });

const font = gothic;

export const metadata = {
  title: "JDI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={font.className}>
        <NextTopLoader />
        <Header />
        <main className="min-h-screen pt-[70px] flex justify-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
